### PR TITLE
Small tweak to make sure obslog is installed, and ensure effsel accepts all J-K values and can be passed isochrone weights

### PR DESCRIPTION
**Pull request by jmackereth**
Hi Julie,

I made a couple of adjustments that ensure that the observation log file you generated gets put in the right place during the module installation. I also made a change to the code for computing the effective selection function that allows you to supply any J-K (previously this errored if you gave J-K less than the blue bin edge). I also made an adjustment that allows the isochrone weights to be given, in case you want to avoid MCMC integration. Perhaps it would be good to check that this gives the same results as your own tests?

Let me know what you think!

Ted

### CODE REVIEW

**Comment by jmackereth** [comment]
I found a couple of weird things happening when I run arbitrary allStar files through the `determine_statistical` - one of these is fixed in the above commit, the other im still investigating.

I noticed that many stars are getting caught by the try/except at the end with a: `'Warning: problem with determine_statistical for b'apogee.apo25m.stars.120-24_btx.2M00342093+3844380'` style comment. Do you know what's happening there? seems like a lot of stars fail here, so would be good to figure out why. Are they just not part of the statistical sample?

^ all of this can wait till after the holidays - so no rush :smile:

**Comment by jmackereth** [comment]
Things to figure out/fix:

- [x]  How are stars observed by both the north and south handled by the `determine_statistical` method in the `apogeeCombinedSelect` object?
 - [x] Are duplicates being handled in the best way possible?
- [x] Is there a way to allow `determine_statistical` in `apogeeCombinedSelect` to use the separate `apogee1Select` and `apogee2Select` objects that make up the final combined object?
- [x] is the combined `determine_statistical` method doing something consistent with what happens when the selection function is being evaluated?
- [x] is it ok to simply remove stars that fall into this north/south category?
- [x] can we make a list of stars that are failing currently

**Comment by jmackereth** [comment]
update on the above questions:

> - [x]  How are stars observed by both the north and south handled by the `determine_statistical` method in the `apogeeCombinedSelect` object?

Previously, these stars were simply labeled as not in the statistical sample. For stars in location IDs observed both N+S (but not necessarily stars observed in both N+S), the `locIndx` that was evaluated to get the completeness of the cohort had two indices and so the boolean statements failed as ambiguous. I added a catch now that figures out if the star from the allStar provided was observed by APO or LCO, then uses the correct entry in the cohort/bin completeness arrays to determine if it is in the statistical sample.

>  - [x] Are duplicates being handled in the best way possible?

I think most of the targets are not actually duplicated between N+S after all, just that the `LOCATION_ID` is the same, and this is what was used for indexing. Using `rmdups=True` to prepare the input allStar file should ensure that this is not an issue. Note that `rmdups=True` whenever specdata is loaded when evaluating the selection function.

> - [x] Is there a way to allow `determine_statistical` in `apogeeCombinedSelect` to use the separate `apogee1Select` and `apogee2Select` objects that make up the final combined object?

I think this wasn't necessary after all, once the correct method for splitting between surveys was introduced in `apogeeCombinedSelect.determine_statistical`.

> - [x] is the combined `determine_statistical` method doing something consistent with what happens when the selection function is being evaluated?

I believe this is the case now, but we should probably do some sort of check.

> - [x] is it ok to simply remove stars that fall into this north/south category?

There is no need to remove these stars now - I _think_ they are handled correctly now!

> - [x] can we make a list of stars that are failing currently

 Julie produced this - I have checked now and these no longer cause an error!

I think now we just need to make some final checks that the selection function looks as we expect. We should also triple check that these locations in the N+S are behaving as we need them to (i.e. that my assertion above that many of the stars were not actually duplicates after all, is correct!).

 If there are really duplicated targets between N+S, we should ensure that these are handled correctly earlier in the process, when the selection function is evaluated. Not sure yet how we should do that...

**Comment by jmackereth** [comment]
I realised there was a small issue with the `survey=` in `apogee.tools.read.allStar` that was leading to pretty much all the APOGEE 2-S targets not being considered in the selection function... Im not sure when this got introduced, but might be causing important problems!

EDIT: I introduced it a few commits ago, whoops! Lucky catch...

**Comment by astrojimig** [comment]
Thanks for all of your hard work, Ted! I will perform some of these final checks with the new version and let you know how they go.

**Pull request merged**
